name: Winterfell Scribe

on:
  schedule:
    - cron: '0 * * * *' # Once every hour
  workflow_dispatch: # Manually triggerable

jobs:
  scribe-work:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push changes

    steps:
    - name: Checkout The Realm
      uses: actions/checkout@v4

    - name: Set up Maester Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Ingredients
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Consult the Visions
      run: python winterfell_scribe.py

    - name: Archive the Knowledge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add streamed_events.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update The Citadel Archives" && git push)
